src/blog/urls.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     urls.py  
   Description :  
   Author :       JHao
   date：          2017/4/13
-------------------------------------------------
   Change Activity:
                   2017/4/13: 
-------------------------------------------------
"""
__author__ = 'JHao'

from blog import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.blog_list, name='list'),
    path('tag/<str:name>/', views.tag, name='tag'),
    path('category/<str:name>/', views.category, name='category'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('archive/', views.archive, name='archive'),
    path('search/', views.search, name='search'),
    path('message/', views.message, name='message'),
    path('getComment/', views.get_comment, name='get_comment'),

]

src/django_blog/urls.py
from django.urls import path, include
from django.contrib import admin
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('', views.index, name='index'),

]

handler404 = views.page_not_found_error
handler500 = views.page_error

src/blog/models.py
# -*- coding: utf-8 -*-
"""
-------------------------------------------------
   File Name：     models.py
   Description :
   Author :       JHao
   date：          2016/11/18
-------------------------------------------------
   Change Activity:
                   2016/11/18:
-------------------------------------------------
"""

from django.db import models
from django.conf import settings


# Create your models here.

class Tag(models.Model):
    tag_name = models.CharField('标签名称', max_length=30)

    def __str__(self):
        return self.tag_name


class Article(models.Model):
    title = models.CharField(max_length=200)  # 博客标题
    category = models.ForeignKey('Category', verbose_name='文章类型', on_delete=models.CASCADE)
    date_time = models.DateField(auto_now_add=True)  # 博客日期
    content = models.TextField(blank=True, null=True)  # 文章正文
    digest = models.TextField(blank=True, null=True)  # 文章摘要
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    view = models.BigIntegerField(default=0)  # 阅读数
    comment = models.BigIntegerField(default=0)  # 评论数
    picture = models.CharField(max_length=200)  # 标题图片地址
    tag = models.ManyToManyField(Tag)  # 标签

    def __str__(self):
        return self.title

    def sourceUrl(self):
        source_url = settings.HOST + '/blog/detail/{id}'.format(id=self.pk)
        return source_url  # 给网易云跟帖使用

    def viewed(self):
        """
        增加阅读数
        :return:
        """
        self.view += 1
        self.save(update_fields=['view'])

    def commenced(self):
        """
        增加评论数
        :return:
        """
        self.comment += 1
        self.save(update_fields=['comment'])

    class Meta:  # 按时间降序
        ordering = ['-date_time']


class Category(models.Model):
    name = models.CharField('文章类型', max_length=30)
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_mod_time = models.DateTimeField('修改时间', auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = "文章类型"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Comment(models.Model):
    title = models.CharField("标题", max_length=100)
    source_id = models.CharField('文章id或source名称', max_length=25)
    create_time = models.DateTimeField('评论时间', auto_now=True)
    user_name = models.CharField('评论用户', max_length=25)
    url = models.CharField('链接', max_length=100)
    comment = models.CharField('评论内容', max_length=500)

src/blog/views.py
# -*- coding: utf-8 -*-
# Create your views here.

import json
from django.http import JsonResponse
from django_blog.util import PageInfo
from blog.models import Article, Comment
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, get_object_or_404


def get_page(request):
    page_number = request.GET.get("page")
    return 1 if not page_number or not page_number.isdigit() else int(page_number)


def index(request):
    _blog_list = Article.objects.all().order_by('-date_time')[0:5]
    _blog_hot = Article.objects.all().order_by('-view')[0:6]
    return render(request, 'blog/index.html', {"blog_list": _blog_list, "blog_hot": _blog_hot})


def blog_list(request):
    """
    列表
    :param request:
    :return:
    """
    page_number = get_page(request)
    blog_count = Article.objects.count()
    page_info = PageInfo(page_number, blog_count)
    _blog_list = Article.objects.all()[page_info.index_start: page_info.index_end]
    return render(request, 'blog/list.html', {"blog_list": _blog_list, "page_info": page_info})


def category(request, name):
    """
    分类
    :param request:
    :param name:
    :return:
    """
    page_number = get_page(request)
    blog_count = Article.objects.filter(category__name=name).count()
    page_info = PageInfo(page_number, blog_count)
    _blog_list = Article.objects.filter(category__name=name)[page_info.index_start: page_info.index_end]
    return render(request, 'blog/category.html', {"blog_list": _blog_list, "page_info": page_info,
                                                  "category": name})


def tag(request, name):
    """
    标签
    :param request:
    :param name
    :return:
    """
    page_number = get_page(request)
    blog_count = Article.objects.filter(tag__tag_name=name).count()
    page_info = PageInfo(page_number, blog_count)
    _blog_list = Article.objects.filter(tag__tag_name=name)[page_info.index_start: page_info.index_end]
    return render(request, 'blog/tag.html', {"blog_list": _blog_list,
                                             "tag": name,
                                             "page_info": page_info})


def archive(request):
    """
    文章归档
    :param request:
    :return:
    """
    _blog_list = Article.objects.values("id", "title", "date_time").order_by('-date_time')
    archive_dict = {}
    for blog in _blog_list:
        pub_month = blog.get("date_time").strftime("%Y年%m月")
        if pub_month in archive_dict:
            archive_dict[pub_month].append(blog)
        else:
            archive_dict[pub_month] = [blog]
    data = sorted([{"date": _[0], "blogs": _[1]} for _ in archive_dict.items()], key=lambda item: item["date"],
                  reverse=True)
    return render(request, 'blog/archive.html', {"data": data})


def message(request):
    return render(request, 'blog/message_board.html', {"source_id": "message"})


@csrf_exempt
def get_comment(request):
    """
    接收畅言的评论回推， post方式回推
    :param request:
    :return:
    """
    arg = request.POST
    data = arg.get('data')
    data = json.loads(data)
    title = data.get('title')
    url = data.get('url')
    source_id = data.get('sourceid')
    if source_id not in ['message']:
        article = Article.objects.get(pk=source_id)
        article.commenced()
    comments = data.get('comments')[0]
    content = comments.get('content')
    user = comments.get('user').get('nickname')
    Comment(title=title, source_id=source_id, user_name=user, url=url, comment=content).save()
    return JsonResponse({"status": "ok"})


def detail(request, pk):
    """
    博文详情
    :param request:
    :param pk:
    :return:
    """
    blog = get_object_or_404(Article, pk=pk)
    blog.viewed()
    return render(request, 'blog/detail.html', {"blog": blog})


def search(request):
    """
    搜索
    :param request:
    :return:
    """
    key = request.GET['key']
    page_number = get_page(request)
    blog_count = Article.objects.filter(title__icontains=key).count()
    page_info = PageInfo(page_number, blog_count)
    _blog_list = Article.objects.filter(title__icontains=key)[page_info.index_start: page_info.index_end]
    return render(request, 'blog/search.html', {"blog_list": _blog_list, "pages": page_info, "key": key})


def page_not_found_error(request, exception):
    return render(request, "404.html", status=404)


def page_error(request):
    return render(request, "404.html", status=500)

src/templates/blog/about.html
{% extends "blog/base.html" %}

{% block title %}
    <title>AboutMe - 烂笔头</title>
{% endblock %}

{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

src/templates/blog/archive.html
{% extends "blog/base.html" %}

{% block title %}
    <title>文章归档｜烂笔头</title>
{% endblock %}

{% block css %}
    <link href="/static/layui/css/layui.css" rel="stylesheet"/>
    <style>
        /* disable layui style */
        .layui-card-header {
            border-bottom: transparent;
        }

        .layui-card {
            background-color: transparent;
        }

        .layui-timeline-axis {
            background-color: transparent;
        }
    </style>
{% endblock %}

{% block content %}
    <section class="mysection">
        <div class="layui-card">
            <div class="layui-card-header">文章归档</div>
            <div class="layui-card-body">
                <ul class="layui-timeline">
                    {% for blog_list in data %}
                        <li class="layui-timeline-item">
                            <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                            <div class="layui-timeline-content layui-text">
                                <h3 class="layui-timeline-title" style="padding:0">{{ blog_list.date }}</h3>
                                <ul>
                                    {% for blog in blog_list.blogs %}
                                        <li>
                                            <em>{{ blog.date_time |date:"d" }}日</em>
                                            <a href="{% url "blog:detail" blog.id %}">{{ blog.title }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </section>
{% endblock %}

{% block js %}
    <script src="/static/layui/layui.js"></script>
{% endblock %}

src/templates/blog/base.html
<!doctype html>
<html>
<head>

    {% block title %}
        <title>烂笔头 - j_hao104的博客</title>
    {% endblock %}

    {% block meta %}
        <meta charset="UTF-8">
        <meta name="keywords" content="Python,爬虫,Django,算法,j_hao104的博客"/>
        <meta name="description" content="j_hao104的博客,一个个人网站，IT技术分享，记录IT生活，提供技术分享和作品分享的个人网站"/>
    {% endblock %}
    <meta name="author" content="j_hao104"/>
    <meta name="baidu-site-verification" content="2HhDg1sekr"/>
    <meta name="google-site-verification" content="gpXH5Aw-1dy2I5NHeRnNFS_P-PSA_d5TOJHn5bBPvSI"/>
    <link rel="shortcut icon" href="/static/images/favicon.ico"/>

    <!--CSS-->
    {% block css %}{% endblock %}
    <link rel="stylesheet" href="/static/css/default.css"/>
    <link rel="stylesheet" href="/static/css/public.css"/>
    <link rel="stylesheet" href="/static/css/animation.css"/>

    <link rel="stylesheet" type="text/css" href="/static/css/skin_1.css" title="qingxin"/>
    <link rel="stylesheet" type="text/css" href="/static/css/skin_2.css" title="jianyue"/>
    <link rel="stylesheet" type="text/css" href="/static/css/skin_3.css" title="qingshuang"/>
    <link rel="stylesheet" href="/static/css/font-icon.css"/>
    <!--JS-->

    <script src="/static/js/jquery.2.1.4.min.js"></script>
    <script src="/static/js/my.js"></script>
    <script>
        $("html").append("<div class='jiazai'><img src='/static/images/icon/loading.gif'/><span>正在加载中请等待...</span></div>")
    </script>
    <script src="/static/js/superbg.min.js"></script>
    <script src="/static/js/superbg-custom.js"></script>
    <script src="/static/js/tooltip.js"></script>
    <script src="/static/js/layer/layer.js"></script>

    <!--[if lte IE 8]>
    <script>window.location.href = 'http://cdn.dmeng.net/upgrade-your-browser.html?referrer=' + location.href;</script>
    <![endif]-->

</head>

<body class="nobg">

<!--导航开始-->
{% include "blog/header.html" %}
<!--导航结束-->

<!--主题框架开始-->
<div class="container">
    <!--左侧开始-->
    {% block content %}
    {% endblock %}
    <!--左侧结束-->

    <!--右侧开始-->
    {% include "blog/right.html" %}
    <!--END右侧-->
</div>
<!--主题框架结束-->


<!---底部开始-->
{% include "blog/footer.html" %}
<!---END底部-->

{% block js %}{% endblock %}

</body>
</html>

src/templates/blog/blogroll.html
<!--友情链接-->
<div class="side-link animation-div">
    <h4 class="index-title"><i class="el-paper-clip"></i>友情链接
        <small>Links</small>
        <a href="mailto:j_hao104@163.com?subject=博客友链互换&body=博客名称:<br> 博客描述:<br>博客地址:"><i class="el el-plus"></i>申请</a>
    </h4>
    <ul>
        {% for blog in blogroll %}
            <li><a href="{{ blog.url }}" target="_blank" title="{{ blog.desc }}">{{ blog.name }}</a></li>
        {% endfor %}
    </ul>
</div>

src/templates/blog/category.html
{% extends "blog/base.html" %}

{% block title %}
    <title>分类：{{ category }} - 烂笔头</title>
{% endblock %}

{% block content %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:list" %}"><i class="el-th-list"></i> 列表&nbsp;&nbsp;> &nbsp;&nbsp;</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">
                共有:<a class="orange-text"> {{ page_info.total_number }} </a>篇</span>
        </h4>
        {% if blog_list %}
            {% include "blog/component/blog_list.html" with blogs=blog_list %}
            {% include "blog/component/pagination.html" with pages=page_info %}
        {% else %}
            <p>暂时没有文章..</p>
        {% endif %}
    </section>

{% endblock %}

src/templates/blog/component/auto_push_baidu.html
<script>
    // 自动提交链接到百度 start
    (function () {
        let bp = document.createElement('script');
        let curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        } else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        let s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
    // end

</script>

src/templates/blog/component/blog_list.html
<div class="arclist">
    <ul>
        {% for blog in blogs %}
            {% if id %}
                <li id="{{ id }}">
                    {% else %}
                <li {% if blog.view > 1000 %} id="tuijian" {% elif article.view > 500 %} id="Hot" {% endif %}>
            {% endif %}
        <div class="arcimg">
            <img src="{{ blog.picture }}"
                 alt="{{ blog.title }}" title="{{ blog.title }}"/>
        </div>
        <div class="arc-right">
            <h4 class="blue-text"><a href="{% url "blog:detail" blog.id %}"
                                     title="{{ blog.title }}">{{ blog.title }}</a></h4>
            <p>{{ blog.digest }}</p>
            <ul>
                <li><a title="发布于 {{ blog.date_time }}  "><i
                        class="el-time"></i> {{ blog.date_time }}</a></li>
                <li><a title="作者： {{ blog.author }}"><i class="el-user"></i>{{ blog.author }}</a>
                </li>
                <li><a title="已有 {{ blog.comment }} 条评论"><i
                        class="el-comment"></i>{{ blog.comment }}</a>
                </li>
                <li><a title="已有 {{ blog.view }} 次浏览"><i class="el-eye-open"></i>{{ blog.view }}</a></li>
                {% for tag in blog.tag.values %}
                    <li class="mob-hidden">
                        <a title="标签: {{ tag.tag_name }}" href="{% url "blog:tag" tag.tag_name %}"><i class="el-tag"></i>{{ tag.tag_name }}</a>&nbsp;
                    </li>
                {% endfor %}
                <li><a href="{% url "blog:list" %}}" title="查看分类"><i
                        class="el-th-list"></i>{{ blog.category }}</a></li>
            </ul>
        </div>
        </li>
        {% endfor %}
    </ul>
</div>

src/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load custom_filter %}

{% block title %}
    <title>{{ blog.title }} - 烂笔头</title>
{% endblock %}

{% block meta %}
    <meta name="keywords"
          content="{{ blog.title }},{% for tag in blog.tag.all %}{{ tag }},{% endfor %}{{ blog.category }}"/>
    <meta name="description" content="{{ blog.digest|safe }}"/>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="/static/css/markdown.css">
    <link rel="stylesheet" href="/static/prism/prism.css">
{% endblock %}

{% block content %}

    <div class="mysection content">
        <article>
            <h3 class="arc-title index-title">{{ blog.title }} </h3>
            <div class="post-line bg-color">
                <ul>
                    <li><a title="{{ blog.author }}发表于{{ blog.date_time }}"><i class="el-time"></i>
                        <time>{{ blog.date_time }}</time>
                    </a></li>
                    <li><a href="#"><i class="el-user"></i>{{ blog.author }}</a></li>
                    <li><a href="#Coon" title="转到评论"><i class="el-comment"></i>{{ blog.comment }}条</a></li>
                    <li><a title="已有 {{ blog.view }} 次浏览"><i class="el-eye-open"></i>{{ blog.view }}</a></li>
                </ul>
            </div>

            <!--文章正文-->
            <div class="article-content bg-color markdown-body">
                <div class="post-content" style="padding: 10px 20px 20px 10px">
                    <div class="BlogAnchor" style="text-indent: 20px; font-size: 14px; margin-bottom: 30px">
                        <p>
                            <b id="AnchorContentToggle" title="收起" style="cursor:pointer;">目录[-]</b>
                        </p>
                        <div class="AnchorContent" id="AnchorContent"></div>
                    </div>
                    {{ blog.content|custom_markdown|safe }}
                </div>
            </div>
            <!--分享-->
            <div class="article-fx"><a class="fx-btn img-circle" href="javascript:;">分享</a>
                <div class="bd-fx arc-bdfx">
                    <i class="el-remove fx-close"></i>
                    <ul class="bdsharebuttonbox">
                        <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                        <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                        <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                        <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
                    </ul>
                    <script>window._bd_share_config = {
                        "common": {
                            "bdSnsKey": {},
                            "bdText": "",
                            "bdMini": "2",
                            "bdMiniList": false,
                            "bdPic": "",
                            "bdStyle": "1",
                            "bdSize": "32"
                        }, "share": {}
                    };
                    with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
                </div>
            </div>
            <!--END 分享-->
            <div class="cyReward " style="text-align: center">
                <div id="cyReward" role="cylabs" data-use="reward" sid="{{ blog.id }}"></div>
            </div>

            <hr>


            <!--标签-->
            <div class="article_tag">
                <ul>
                    <li><a href="{% url "blog:category" blog.category %}"
                           title="分类：{{ blog.category }}">{{ blog.category }}</a></li>
                    {% for tag in blog.tag.all %}
                        <li><a href="{% url "blog:tag" name=tag.tag_name %}"
                               title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a>&nbsp;
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="cyEmoji" style="text-align: center">
                <div id="cyEmoji" role="cylabs" data-use="emoji" sid="{{ blog.id }}"></div>
            </div>

        </article>

        <!--评论表单-->
        {% include "blog/message.html"  with source_id=blog.id %}

    </div>


{% endblock %}

{% include 'blog/component/auto_push_baidu.html' %}



{% block js %}

    <script src="/static/js/jquery.2.1.4.min.js"></script>

    <script src="/static/prism/clipboard.min.js"></script>
    <script src="/static/prism/prism.js" charset="utf-8"></script>

    <script type="text/javascript"
            src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$', '$']]},
            messageStyle: "none"
        });


    </script>

    <script type="text/javascript" src="https://changyan.sohu.com/js/changyan.labs.https.js?appid=cyt6A5N47"></script>

    <script>
        function GenerateContentList() {
            $(".post-content").find("h2,h3").each(function (i, item) {
                var tag = $(item).get(0).localName;
                $(item).attr("id", "wow" + i);
                $("#AnchorContent").append('<li><a class="new' + tag + ' anchor-link"  href="#wow' + i + '">' + $(this).text() + '</a></li>');
                $(".newh2").css("margin-left", 0);
                $(".newh3").css("margin-left", 20);
                $(".newh4").css("margin-left", 40);
                $(".newh5").css("margin-left", 60);
                $(".newh6").css("margin-left", 80);
            });
            $("#AnchorContentToggle").click(function () {
                var text = $(this).html();
                if (text == "目录[-]") {
                    $(this).html("目录[+]");
                    $(this).attr({"title": "展开"});
                } else {
                    $(this).html("目录[-]");
                    $(this).attr({"title": "收起"});
                }
                $("#AnchorContent").toggle();
            });
        }

        GenerateContentList();
    </script>

{% endblock %}

src/templates/blog/footer.html
<footer>
    <!--底部导航-->
    <div class="foot-nav">
        <div class="copy-right"><span>CopyRight &#169; 2015-2020 j_hao104's博客 &#160;&#160;&#160;     Design by j_hao104</span></div>
        <div class="license bottom-nav">
            <a href="http://www.miitbeian.gov.cn">@2017 spiderpy.cn 	蜀ICP备17012574号-1</a></span>
        </div>
    </div>
    <div id="toTop">Back to Top</div>
    <script>
    </script>


</footer>

src/templates/blog/header.html
<header class="myheader">
    <div class="top">
        <!--头像左边部分-->
        <div class="top-left">
            <div class="logo"><a href="{% url "blog:index" %}"><img src="/static/images/h.gif" alt=""/></a></div>

            <!--滚动消息-->
            <div class="web-xiaoxi">
                <i class="el-speaker"></i>
                <ul class="mulitline">
                    <li>烂笔头 - j_hao104的博客</li>
                    <li>现已开放源码下载</li>
                    <li>喜欢的可以在github follow我</li>
                </ul>
            </div>
            <!--END 消息 -->

            <!--手机菜单按钮-->
            <div class="mobile-nav"><i class="el-lines"></i><i class="el-remove"></i></div>
        </div>
        <!--电脑导航开始-->
        <nav class="mynav">
            <ul class="orange-text">
                <li class=""><a href="{% url "blog:index" %}">首页</a></li>
                <li><a href="{% url "blog:list" %}">博客</a></li>
                <li class='drop'>
                    <a href="JavaScript:;">分类<i class='el-chevron-down'></i></a>
                    <div class="drop-nav orange-text">
                        <ul>
                            {% for category in category_list %}
                                <li><a href="{% url "blog:category" name=category.name %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>
                <li><a href="{% url "blog:message" %}">留言</a></li>
            </ul>
        </nav>

        <!--这里是手机导航-->
        <div class="mob-menu">
            <!--手机顶部搜索-->
            <div class="search ">
                <form action="{% url "blog:search" %}" method="get">
                    <div class="search-index">
                        <input name="name" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                               onblur="this.placeholder='请输入关键字'"/>
                        <i class="el-search"><input value=" " type="submit"/></i>
                    </div>
                </form>
            </div>
            <!--手机下拉菜单-->
            <ul>
                <li><a href="{% url "blog:index" %}">首页</a></li>
                <li><a href="{% url "blog:list" %}">博客</a></li>
                <li class='mob-drop'>
                    <a href="JavaScript:;">分类</a>
                    <ul class="mob-dropmenu">
                        {% for category in category_list %}
                            <li><a href="{% url "blog:category" name=category.name %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url "blog:archive" %}">归档</a></li>
                <li><a href="{% url "blog:message" %}">留言</a></li>
            </ul>
        </div>
    </div>
    <!--换肤--->
    <script src="/static/js/skin.js"></script>
    <div class="select-skin">
        <div class="skin-btn">
            <a href="javascript:void(0);" class="skin-btn-open">换<br>肤</a>
        </div>

        <div class="skin-content">
            <h1>选择风格<span class="skin-close">关闭</span></h1>
            <div class="skin-content-list">
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingxin'); return false;" class="btn1">清新</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('jianyue'); return false;" class="btn2">简约</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingshuang'); return false;"
                                          class="btn3">清爽</a></div>
            </div>
        </div>
    </div>
</header>

src/templates/blog/message.html
<h3 class="form-btn blue-text"><a href="javascript:;"><i class="el-edit"></i>我要留言 / 展开表单</a></h3>
<div id="Coon" class="form-zd form-in">
    {% include 'blog/component/changyan.html' %}
</div>

src/templates/blog/search.html
{% extends "blog/base.html" %}

{% block title %}
    <title>搜索:{{ key }} | 烂笔头</title>
{% endblock %}

{% block content %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:list" %}"><i class="el-search"></i>搜索到<b class="lable">{{ key }}</b>相关结果</a>
            <span style="float:right;margin-right:10px;">
                共:<a class="orange-text"> {{ pages.total_number }} </a>篇</span>
        </h4>
        {% if blog_list %}
            {% include "blog/component/blog_list.html" with blogs=blog_list %}

            <div class="pagination">
                <div class="list-page">
                    <ul class="post-data">
                        <li><a>第 {{ pages.current_page }} - {{ pages.total_page }} 页</a> <a>共 {{ pages.total_number }}
                            条</a></li>
                    </ul>
                </div>
                <ul>
                    {% if pages.current_page == 1 %}
                        <li class="active"><a>首页</a></li>
                    {% else %}
                        <li><a href="?key={{ key }}&page=1">首页</a></li>
                    {% endif %}

                    {% if pages.current_page >= 2 %}
                        <li><a href="?key={{ key }}&page={{ pages.current_page|add:-1 }}">上一页</a></li>
                    {% else %}
                        <li class="active"><a>上一页</a></li>
                    {% endif %}

                    {% if pages.current_page < pages.total_page %}
                        <li><a href="?key={{ key }}&page={{ pages.current_page|add:1 }}">下一页</a></li>
                        <li><a href="?key={{ key }}&page={{ pages.total_page }}">尾页</a></li>
                    {% else %}
                        <li class="active"><a>下一页</a></li>
                        <li class="active"><a>尾页</a></li>
                    {% endif %}
                </ul>
            </div>

        {% else %}
            <p>暂时没有文章..</p>
        {% endif %}
    </section>

{% endblock %}

src/templates/blog/tag.html
{% extends "blog/base.html" %}

{% block title %}
    <title>标签：{{ tag }} - 烂笔头</title>
{% endblock %}

{% block content %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "blog:tag" name=tag %}"><i class="el-tag"></i> 标签<b class="lable">{{ tag }}</b></a>
            <span style="float:right;margin-right:10px;">共有:
                <a class="orange-text"> {{ page_info.total_number }} </a>篇</span>
        </h4>
        {% if blog_list %}
            {% include "blog/component/blog_list.html" with blogs=blog_list %}
            {% include "blog/component/pagination.html" with pages=page_info %}
        {% else %}
            <p>暂时没有文章..</p>
        {% endif %}
    </section>

{% endblock %}